trigger:
- main

pool:
  name: Default # personal private agent pool
  demands: Platform -equals Windows

steps:
- task: Npm@1
  inputs:
    command: publish
    publishRegistry: useExternalRegistry
    publishEndpoint: 'NpmGithubRegistryConnection'
